package com.example.squirrelwarehouse;

import java.util.HashMap;

public class Category {

    String product;
    HashMap<String,Integer> map = new HashMap<>();

    Category(String product) {
        this.product = product;

        setDataInit(); // 데이터 초기화. 1000개의 데이터 매핑하는 함수
    }

    private void setDataInit() {
        // 디지털 가전 > 0
        map.put("cellular telephone",0);
        map.put("computer keyboard",0);
        map.put("desktop computer",0);
        map.put("digital clock",0);
        map.put("digital watch",0);
        map.put("dishwasher",0);
        map.put("electric fan",0);
        map.put("espresso maker",0);
        map.put("hand-held computer",0);
        map.put("hard disc",0);
        map.put("iPod",0);
        map.put("joystick",0);
        map.put("laptop",0);
        map.put("lens cap",0);
        map.put("loudspeaker",0);
        map.put("modem",0);
        map.put("monitor",0);
        map.put("mouse",0);
        map.put("notebook",0);
        map.put("oscilloscope",0);

        map.put("parking meter",0);
        map.put("pay-phone",0);
        map.put("photocopier",0);
        map.put("Polaroid camera",0);
        map.put("printer",0);
        map.put("projector",0);
        map.put("radiator",0);
        map.put("radio",0);
        map.put("reflex camera",0);
        map.put("refrigerator",0);
        map.put("remote control",0);
        map.put("rotisserie",0);
        map.put("safe",0);
        map.put("scale",0);
        map.put("screen",0);
        map.put("sewing machine",0);
        map.put("space bar",0);
        map.put("space heater",0);
        map.put("stove",0);
        map.put("switch",0);
        map.put("table lamp",0);
        map.put("tape player",0);
        map.put("television",0);
        map.put("toaster",0);
        map.put("typewriter keyboard",0);
        map.put("vacuum",0);
        map.put("waffle iron",0);
        map.put("washer",0);





        // 생활/인테리어 > 1
        map.put("analog clock",1);
        map.put("apron",1);
        map.put("Band Aid",1);
        map.put("bannister",1);
        map.put("barber chair",1);
        map.put("barrel",1);
        map.put("bassinet",1);
        map.put("bathing cap",1);
        map.put("bath towel",1);
        map.put("bathtub",1);
        map.put("beach wagon",1);
        map.put("beaker",1);
        map.put("beer bottle",1);
        map.put("beer glass",1);
        map.put("bell cote",1);
        map.put("bookcase",1);
        map.put("bottlecap",1);

        map.put("oxygen mask",1);
        map.put("pajama",1);
        map.put("paper towel",1);
        map.put("park bench",1);
        map.put("passenger car",1);
        map.put("pedestal",1);
        map.put("picket fence",1);
        map.put("pickup",1);
        map.put("pill bottle",1);
        map.put("pillow",1);
        map.put("pitcher",1);
        map.put("plate rack",1);
        map.put("plunger",1);
        map.put("pot",1);
        map.put("power drill",1);
        map.put("prayer rug",1);
        map.put("purse",1);
        map.put("quilt",1);
        map.put("rain barrel",1);
        map.put("recreational vehicle",1);
        map.put("reel",1);
        map.put("rocking chair",1);
        map.put("saltshaker",1);
        map.put("scabbard",1);
        map.put("shoji",1);
        map.put("shopping basket",1);
        map.put("shopping cart",1);
        map.put("shovel",1);
        map.put("shower curtain",1);
        map.put("sliding door",1);
        map.put("soap dispenser",1);
        map.put("soup bowl",1);
        map.put("spatula",1);
        map.put("stone wall",1);
        map.put("strainer",1);
        map.put("studio couch",1);
        map.put("teapot",1);
        map.put("teddy",1);
        map.put("theater curtain",1);
        map.put("thimble",1);
        map.put("throne",1);
        map.put("tile roof",1);
        map.put("toilet seat",1);
        map.put("torch",1);
        map.put("tray",1);
        map.put("tub",1);
        map.put("umbrella",1);
        map.put("vase",1);
        map.put("wall clock",1);
        map.put("wardrobe",1);
        map.put("washbasin",1);
        map.put("water bottle",1);
        map.put("water jug",1);
        map.put("whiskey jug",1);
        map.put("window screen",1);
        map.put("window shade",1);
        map.put("wok",1);
        map.put("wooden spoon",1);
        map.put("plate",1);
        map.put("hot pot",1);
        map.put("cup",1);
        map.put("toilet tissue",1);

        map.put("broom",1);
        map.put("bucket",1);
        map.put("buckle",1);
        map.put("caldron",1);
        map.put("candle",1);
        map.put("can opener",1);
        map.put("car mirror",1);
        map.put("carpenter's kit",1);
        map.put("carton",1);
        map.put("chainlink fence",1);
        map.put("chain saw",1);
        map.put("chiffonier",1);
        map.put("chime",1);
        map.put("china cabinet",1);
        map.put("cleaver",1);
        map.put("cocktail shaker",1);
        map.put("coffee mug",1);
        map.put("coffeepot",1);
        map.put("coil",1);
        map.put("combination lock",1);
        map.put("confectionery",1);
        map.put("corkscrew",1);
        map.put("cradle",1);
        map.put("crate",1);
        map.put("crib",1);
        map.put("Crock Pot",1);
        map.put("crutch",1);
        map.put("desk",1);
        map.put("dial telephone",1);
        map.put("diaper",1);
        map.put("dining table",1);
        map.put("dishrag",1);
        map.put("disk brake",1);
        map.put("doormat",1);
        map.put("Dutch oven",1);
        map.put("entertainment center",1);
        map.put("fire screen",1);
        map.put("folding chair",1);
        map.put("fountain",1);
        map.put("four-poster",1);
        map.put("frying pan",1);
        map.put("goblet",1);
        map.put("greenhouse",1);
        map.put("grille",1);
        map.put("hammer",1);
        map.put("hamper",1);
        map.put("hand blower",1);
        map.put("hatchet",1);
        map.put("home theater",1);
        map.put("hook",1);
        map.put("hourglass",1);
        map.put("iron",1);
        map.put("knot",1);
        map.put("ladle",1);
        map.put("lampshade",1);
        map.put("lawn mower",1);
        map.put("lighter",1);
        map.put("mailbox",1);
        map.put("mask",1);
        map.put("matchstick",1);
        map.put("measuring cup",1);
        map.put("medicine chest",1);
        map.put("microwave",1);
        map.put("milk can",1);
        map.put("mixing bowl",1);
        map.put("mobile home",1);
        map.put("mosquito net",1);
        map.put("mousetrap",1);
        map.put("muzzle",1);



        // 스포츠/레저 > 2
        map.put("balance beam",2);
        map.put("barbell",2);
        map.put("baseball",2);
        map.put("basketball",2);
        map.put("bicycle-built-for-two",2);
        map.put("binder",2);
        map.put("bobsled",2);

        map.put("paddle",2);
        map.put("parachute",2);
        map.put("parallel bars",2);
        map.put("ping-pong ball",2);
        map.put("pool table",2);
        map.put("puck",2);
        map.put("punching bag",2);
        map.put("racer",2);
        map.put("racket",2);
        map.put("rugby ball",2);
        map.put("running shoe",2);
        map.put("schooner",2);
        map.put("scoreboard",2);
        map.put("ski",2);
        map.put("ski mask",2);
        map.put("sleeping bag",2);
        map.put("snorkel",2);
        map.put("snowmobile",2);
        map.put("soccer ball",2);
        map.put("speedboat",2);
        map.put("sports car",2);
        map.put("swimming trunks",2);
        map.put("swing",2);
        map.put("tennis ball",2);
        map.put("tricycle",2);
        map.put("trimaran",2);
        map.put("unicycle",2);
        map.put("volleyball",2);
        map.put("ballplayer",2);
        map.put("scuba diver",2);

        map.put("bulletproof vest",2);
        map.put("canoe",2);
        map.put("car wheel",2);
        map.put("cliff dwelling",2);
        map.put("convertible",2);
        map.put("crash helmet",2);
        map.put("croquet ball",2);
        map.put("dogsled",2);
        map.put("dumbbell",2);
        map.put("football helmet",2);
        map.put("gasmask",2);
        map.put("go-kart",2);
        map.put("golf ball",2);
        map.put("golfcart",2);
        map.put("gondola",2);
        map.put("horizontal bar",2);
        map.put("jersey",2);
        map.put("knee pad",2);
        map.put("magnetic compass",2);
        map.put("maillot",2);
        map.put("mountain bike",2);
        map.put("mountain tent",2);
        map.put("neck brace",2);
        map.put("odometer",2);
        map.put("oil filter",2);



        // 패션/뷰티/미용 > 3
        map.put("puffer",3);
        map.put("abaya",3);
        map.put("academic gown",3);
        map.put("backpack",3);
        map.put("bikini",3);
        map.put("bolo tie",3);
        map.put("bonnet",3);
        map.put("bow tie",3);

        map.put("overskirt",3);
        map.put("perfume",3);
        map.put("pickelhaube",3);
        map.put("poncho",3);
        map.put("sandal",3);
        map.put("sarong",3);
        map.put("shower cap",3);
        map.put("sock",3);
        map.put("sombrero",3);
        map.put("stole",3);
        map.put("suit",3);
        map.put("sunglass",3);
        map.put("sunglasses",3);
        map.put("sunscreen",3);
        map.put("sweatshirt",3);
        map.put("trench coat",3);
        map.put("velvet",3);
        map.put("vestment",3);
        map.put("wig",3);
        map.put("Windsor tie",3);
        map.put("groom",3);

        map.put("brassiere",3);
        map.put("breastplate",3);
        map.put("cardigan",3);
        map.put("chain",3);
        map.put("chain mail",3);
        map.put("Christmas stocking",3);
        map.put("cloak",3);
        map.put("clog",3);
        map.put("cowboy boot",3);
        map.put("cowboy hat",3);
        map.put("cuirass",3);
        map.put("face powder",3);
        map.put("feather boa",3);
        map.put("fur coat",3);
        map.put("gown",3);
        map.put("hair slide",3);
        map.put("hair spray",3);
        map.put("handkerchief",3);
        map.put("hoopskirt",3);
        map.put("jean",3);
        map.put("kimono",3);
        map.put("lab coat",3);
        map.put("liner",3);
        map.put("lipstick",3);
        map.put("Loafer",3);
        map.put("lotion",3);
        map.put("mailbag",3);
        map.put("military uniform",3);
        map.put("miniskirt",3);
        map.put("mitten",3);
        map.put("mortarboard",3);
        map.put("nail",3);
        map.put("necklace",3);



        // 문구/완구 > 4
        map.put("Old English sheepdog",4);
        map.put("Shetland sheepdog",4);
        map.put("collie",4);
        map.put("Border collie",4);
        map.put("Bouvier des Flandres",4);
        map.put("Rottweiler",4);
        map.put("German shepherd",4);
        map.put("Doberman",4);
        map.put("miniature pinscher",4);
        map.put("Greater Swiss Mountain dog",4);
        map.put("Bernese mountain dog",4);
        map.put("Appenzeller",4);
        map.put("EntleBucher",4);
        map.put("boxer",4);
        map.put("bull mastiff",4);
        map.put("Tibetan mastiff",4);
        map.put("French bulldog",4);
        map.put("Great Dane",4);
        map.put("Saint Bernard",4);
        map.put("Eskimo dog",4);
        map.put("malamute",4);
        map.put("Siberian husky",4);
        map.put("dalmatian",4);
        map.put("affenpinscher",4);
        map.put("basenji",4);
        map.put("pug",4);
        map.put("Leonberg",4);
        map.put("Newfoundland",4);
        map.put("Great Pyrenees",4);
        map.put("Samoyed",4);
        map.put("Pomeranian",4);
        map.put("chow",4);
        map.put("keeshond",4);
        map.put("Brabancon griffon",4);
        map.put("Pembroke",4);
        map.put("Cardigan",4);
        map.put("toy poodle",4);
        map.put("miniature poodle",4);
        map.put("standard poodle",4);
        map.put("Mexican hairless",4);
        map.put("timber wolf",4);
        map.put("white wolf",4);
        map.put("red wolf",4);
        map.put("coyote",4);
        map.put("dingo",4);
        map.put("dhole",4);
        map.put("African hunting dog",4);
        map.put("hyena",4);
        map.put("red fox",4);
        map.put("kit fox",4);
        map.put("Arctic fox",4);
        map.put("grey fox",4);
        map.put("tabby",4);
        map.put("tiger cat",4);
        map.put("Persian cat",4);
        map.put("Siamese cat",4);
        map.put("Egyptian cat",4);
        map.put("cougar",4);
        map.put("lynx",4);
        map.put("leopard",4);
        map.put("snow leopard",4);
        map.put("jaguar",4);
        map.put("lion",4);
        map.put("tiger",4);
        map.put("cheetah",4);
        map.put("brown bear",4);
        map.put("American black bear",4);
        map.put("ice bear",4);
        map.put("sloth bear",4);
        map.put("mongoose",4);
        map.put("meerkat",4);
        map.put("tiger beetle",4);
        map.put("ladybug",4);
        map.put("ground beetle",4);
        map.put("long-horned beetle",4);
        map.put("leaf beetle",4);
        map.put("dung beetle",4);
        map.put("rhinoceros beetle",4);
        map.put("weevil",4);
        map.put("fly",4);
        map.put("bee",4);
        map.put("ant",4);
        map.put("grasshopper",4);
        map.put("cricket",4);
        map.put("walking stick",4);
        map.put("cockroach",4);
        map.put("mantis",4);
        map.put("cicada",4);
        map.put("leafhopper",4);
        map.put("lacewing",4);
        map.put("dragonfly",4);
        map.put("damselfly",4);
        map.put("admiral",4);
        map.put("ringlet",4);
        map.put("monarch",4);
        map.put("cabbage butterfly",4);
        map.put("sulphur butterfly",4);
        map.put("lycaenid",4);
        map.put("starfish",4);
        map.put("sea urchin",4);
        map.put("sea cucumber",4);
        map.put("wood rabbit",4);
        map.put("hare",4);
        map.put("Angora",4);
        map.put("hamster",4);
        map.put("porcupine",4);
        map.put("fox squirrel",4);
        map.put("marmot",4);
        map.put("beaver",4);
        map.put("guinea pig",4);
        map.put("sorrel",4);
        map.put("zebra",4);
        map.put("hog",4);
        map.put("wild boar",4);
        map.put("warthog",4);
        map.put("hippopotamus",4);
        map.put("ox",4);
        map.put("water buffalo",4);
        map.put("bison",4);
        map.put("ram",4);
        map.put("bighorn",4);
        map.put("ibex",4);
        map.put("hartebeest",4);
        map.put("impala",4);
        map.put("gazelle",4);
        map.put("Arabian camel",4);
        map.put("llama",4);
        map.put("weasel",4);
        map.put("mink",4);
        map.put("polecat",4);
        map.put("black-footed ferret",4);
        map.put("otter",4);
        map.put("skunk",4);
        map.put("badger",4);
        map.put("armadillo",4);
        map.put("three-toed sloth",4);
        map.put("orangutan",4);
        map.put("gorilla",4);
        map.put("chimpanzee",4);
        map.put("gibbon",4);
        map.put("siamang",4);
        map.put("guenon",4);
        map.put("patas",4);
        map.put("baboon",4);
        map.put("macaque",4);
        map.put("langur",4);
        map.put("colobus",4);
        map.put("proboscis monkey",4);
        map.put("marmoset",4);
        map.put("capuchin",4);
        map.put("howler monkey",4);
        map.put("titi",4);
        map.put("spider monkey",4);
        map.put("squirrel monkey",4);
        map.put("Madagascar cat",4);
        map.put("indri",4);
        map.put("Indian elephant",4);
        map.put("African elephant",4);
        map.put("lesser panda",4);
        map.put("giant panda",4);
        map.put("barracouta",4);
        map.put("eel",4);
        map.put("coho",4);
        map.put("rock beauty",4);
        map.put("anemone fish",4);
        map.put("sturgeon",4);
        map.put("gar",4);
        map.put("lionfish",4);
        map.put("aircraft carrier",4);
        map.put("airliner",4);
        map.put("airship",4);
        map.put("abacus",4);
        map.put("altar",4);
        map.put("ambulance",4);
        map.put("amphibian",4);
        map.put("balloon",4);
        map.put("ballpoint",4);
        map.put("barometer",4);
        map.put("barrow",4);
        map.put("bearskin",4);
        map.put("binoculars",4);
        map.put("birdhouse",4);
        map.put("boathouse",4);
        map.put("bookshop",4);
        map.put("bow",4);

        map.put("padlock",4);
        map.put("paintbrush",4);
        map.put("pencil box",4);
        map.put("pencil sharpener",4);
        map.put("petri dish",4);
        map.put("piggy bank",4);
        map.put("rubber eraser",4);
        map.put("rule",4);
        map.put("safety pin",4);
        map.put("screw",4);
        map.put("screwdriver",4);
        map.put("slide rule",4);
        map.put("steam locomotive",4);
        map.put("steel arch bridge",4);
        map.put("stethoscope",4);
        map.put("stopwatch",4);
        map.put("streetcar",4);
        map.put("school bus",4);
        map.put("police van",4);
        map.put("rifle",4);
        map.put("revolver",4);
        map.put("space shuttle",4);
        map.put("submarine",4);
        map.put("tank",4);
        map.put("tow truck",4);
        map.put("toyshop",4);
        map.put("tractor",4);
        map.put("trailer truck",4);
        map.put("tripod",4);
        map.put("trolleybus",4);
        map.put("wallet",4);
        map.put("warplane",4);
        map.put("whistle",4);
        map.put("wool",4);
        map.put("yawl",4);

        map.put("bullet train",4);
        map.put("cab",4);
        map.put("cannon",4);
        map.put("carousel",4);
        map.put("cash machine",4);
        map.put("castle",4);
        map.put("catamaran",4);
        map.put("crane",4);
        map.put("electric locomotive",4);
        map.put("envelope",4);
        map.put("file",4);
        map.put("fireboat",4);
        map.put("fire engine",4);
        map.put("forklift",4);
        map.put("fountain pen",4);
        map.put("freight car",4);
        map.put("garbage truck",4);
        map.put("grocery store",4);
        map.put("half track",4);
        map.put("holster",4);
        map.put("jack-o'-lantern",4);
        map.put("jigsaw puzzle",4);
        map.put("letter opener",4);
        map.put("loupe",4);
        map.put("maze",4);
        map.put("minibus",4);
        map.put("minivan",4);
        map.put("missile",4);
        map.put("Model T",4);
        map.put("mortar",4);
        map.put("moving van",4);




        // 도서 > 5
        map.put("comic book",5);
        map.put("book jacket",5);


        // 음악 > 6
        map.put("accordion",6);
        map.put("acoustic guitar",6);
        map.put("banjo",6);
        map.put("bassoon",6);

        map.put("panpipe",6);
        map.put("pick",6);
        map.put("sax",6);
        map.put("steel drum",6);
        map.put("trombone",6);
        map.put("violin",6);

        map.put("cassette",6);
        map.put("cassette player",6);
        map.put("CD player",6);
        map.put("cello",6);
        map.put("cornet",6);
        map.put("drum",6);
        map.put("drumstick",6);
        map.put("electric guitar",6);
        map.put("flute",6);
        map.put("French horn",6);
        map.put("gong",6);
        map.put("grand piano",6);
        map.put("harmonica",6);
        map.put("harp",6);
        map.put("maraca",6);
        map.put("marimba",6);
        map.put("microphone",6);
        map.put("oboe",6);
        map.put("ocarina",6);
        map.put("organ",6);



        // 기타 > 7
        map.put("apiary",7);
        map.put("ashcan",7);
        map.put("assault rifle",7);
        map.put("bakery",7);
        map.put("barbershop",7);
        map.put("barn",7);
        map.put("beacon",7);
        map.put("brass",7);

        map.put("oxcart",7);
        map.put("packet",7);
        map.put("paddlewheel",7);
        map.put("palace",7);
        map.put("patio",7);
        map.put("pier",7);
        map.put("pinwheel",7);
        map.put("pirate",7);
        map.put("plane",7);
        map.put("planetarium",7);
        map.put("plastic bag",7);
        map.put("plow",7);
        map.put("pole",7);
        map.put("pop bottle",7);
        map.put("potter's wheel",7);
        map.put("prison",7);
        map.put("projectile",7);
        map.put("quill",7);
        map.put("radio telescope",7);
        map.put("restaurant",7);
        map.put("seat belt",7);
        map.put("shield",7);
        map.put("shoe shop",7);
        map.put("slot",7);
        map.put("snowplow",7);
        map.put("solar dish",7);
        map.put("spider web",7);
        map.put("spindle",7);
        map.put("spotlight",7);
        map.put("stage",7);
        map.put("stretcher",7);
        map.put("stupa",7);
        map.put("sundial",7);
        map.put("suspension bridge",7);
        map.put("swab",7);
        map.put("syringe",7);
        map.put("thatch",7);
        map.put("thresher",7);
        map.put("tobacco shop",7);
        map.put("totem pole",7);
        map.put("triumphal arch",7);
        map.put("turnstile",7);
        map.put("upright",7);
        map.put("vault",7);
        map.put("vending machine",7);
        map.put("viaduct",7);
        map.put("water tower",7);
        map.put("wine bottle",7);
        map.put("wing",7);
        map.put("worm fence",7);
        map.put("wreck",7);
        map.put("yurt",7);
        map.put("web site",7);
        map.put("crossword puzzle",7);
        map.put("street sign",7);
        map.put("traffic light",7);
        map.put("menu",7);
        map.put("guacamole",7);
        map.put("consomme",7);
        map.put("trifle",7);
        map.put("ice cream",7);
        map.put("ice lolly",7);
        map.put("French loaf",7);
        map.put("bagel",7);
        map.put("pretzel",7);
        map.put("cheeseburger",7);
        map.put("hotdog",7);
        map.put("mashed potato",7);
        map.put("head cabbage",7);
        map.put("broccoli",7);
        map.put("cauliflower",7);
        map.put("zucchini",7);
        map.put("spaghetti squash",7);
        map.put("acorn squash",7);
        map.put("butternut squash",7);
        map.put("cucumber",7);
        map.put("artichoke",7);
        map.put("bell pepper",7);
        map.put("cardoon",7);
        map.put("mushroom",7);
        map.put("Granny Smith",7);
        map.put("strawberry",7);
        map.put("orange",7);
        map.put("lemon",7);
        map.put("fig",7);
        map.put("pineapple",7);
        map.put("banana",7);
        map.put("jackfruit",7);
        map.put("custard apple",7);
        map.put("pomegranate",7);
        map.put("hay",7);
        map.put("carbonara",7);
        map.put("chocolate sauce",7);
        map.put("dough",7);
        map.put("meat loaf",7);
        map.put("pizza",7);
        map.put("potpie",7);
        map.put("burrito",7);
        map.put("red wine",7);
        map.put("espresso",7);
        map.put("eggnog",7);
        map.put("alp",7);
        map.put("bubble",7);
        map.put("cliff",7);
        map.put("coral reef",7);
        map.put("geyser",7);
        map.put("lakeside",7);
        map.put("promontory",7);
        map.put("sandbar",7);
        map.put("seashore",7);
        map.put("valley",7);
        map.put("volcano",7);
        map.put("rapeseed",7);
        map.put("daisy",7);
        map.put("yellow lady's slipper",7);
        map.put("corn",7);
        map.put("acorn",7);
        map.put("hip",7);
        map.put("buckeye",7);
        map.put("coral fungus",7);
        map.put("agaric",7);
        map.put("gyromitra",7);
        map.put("stinkhorn",7);
        map.put("earthstar",7);
        map.put("hen-of-the-woods",7);
        map.put("bolete",7);
        map.put("ear",7);

        map.put("breakwater",7);
        map.put("butcher shop",7);
        map.put("chest",7);
        map.put("church",7);
        map.put("cinema",7);
        map.put("container ship",7);
        map.put("dam",7);
        map.put("dock",7);
        map.put("dome",7);
        map.put("drilling platform",7);
        map.put("flagpole",7);
        map.put("gas pump",7);
        map.put("guillotine",7);
        map.put("harvester",7);
        map.put("honeycomb",7);
        map.put("horse cart",7);
        map.put("jeep",7);
        map.put("jinrikisha",7);
        map.put("library",7);
        map.put("lifeboat",7);
        map.put("limousine",7);
        map.put("lumbermill",7);
        map.put("manhole cover",7);
        map.put("maypole",7);
        map.put("megalith",7);
        map.put("monastery",7);
        map.put("moped",7);
        map.put("mosque",7);
        map.put("motor scooter",7);
        map.put("nipple",7);
        map.put("obelisk",7);




    }

    private int getCategory() {  // 카테고리 번호 반환 0~7

        return map.get(product);

    }

}